sudo: false
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
script: mvn clean verify
after_success:
  - mvn jacoco:report coveralls:jacoco
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6538a0fe57a3a469fc46
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
