sudo: false
language: java
jdk:
  - oraclejdk8
env: DISPLAY=:99.0
before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start
script: 
  - export
  - mvn clean verify
after_success:
  - mvn jacoco:report coveralls:jacoco
after_failure: cat /home/travis/build/karandit/confetti/00_tests/plugins/org.confetti.tests.xml/target/surefire-reports/*
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6538a0fe57a3a469fc46
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
