package org.confetti.xml.core;

import org.confetti.xml.core.space.ConstraintActivitiesOccupyMaxDifferentRooms;
import org.confetti.xml.core.space.ConstraintActivitiesSameRoomIfConsecutive;
import org.confetti.xml.core.space.ConstraintActivityPreferredRoom;
import org.confetti.xml.core.space.ConstraintActivityPreferredRooms;
import org.confetti.xml.core.space.ConstraintActivityTagPreferredRoom;
import org.confetti.xml.core.space.ConstraintActivityTagPreferredRooms;
import org.confetti.xml.core.space.ConstraintBasicCompulsorySpace;
import org.confetti.xml.core.space.ConstraintRoomNotAvailableTimes;
import org.confetti.xml.core.space.ConstraintStudentsMaxBuildingChangesPerDay;
import org.confetti.xml.core.space.ConstraintStudentsMaxBuildingChangesPerWeek;
import org.confetti.xml.core.space.ConstraintStudentsMinGapsBetweenBuildingChanges;
import org.confetti.xml.core.space.ConstraintStudentsSetHomeRoom;
import org.confetti.xml.core.space.ConstraintStudentsSetHomeRooms;
import org.confetti.xml.core.space.ConstraintStudentsSetMaxBuildingChangesPerDay;
import org.confetti.xml.core.space.ConstraintStudentsSetMaxBuildingChangesPerWeek;
import org.confetti.xml.core.space.ConstraintStudentsSetMinGapsBetweenBuildingChanges;
import org.confetti.xml.core.space.ConstraintSubjectActivityTagPreferredRoom;
import org.confetti.xml.core.space.ConstraintSubjectActivityTagPreferredRooms;
import org.confetti.xml.core.space.ConstraintSubjectPreferredRoom;
import org.confetti.xml.core.space.ConstraintSubjectPreferredRooms;
import org.confetti.xml.core.space.ConstraintTeacherHomeRoom;
import org.confetti.xml.core.space.ConstraintTeacherHomeRooms;
import org.confetti.xml.core.space.ConstraintTeacherMaxBuildingChangesPerDay;
import org.confetti.xml.core.space.ConstraintTeacherMaxBuildingChangesPerWeek;
import org.confetti.xml.core.space.ConstraintTeacherMinGapsBetweenBuildingChanges;
import org.confetti.xml.core.space.ConstraintTeachersMaxBuildingChangesPerDay;
import org.confetti.xml.core.space.ConstraintTeachersMaxBuildingChangesPerWeek;
import org.confetti.xml.core.space.ConstraintTeachersMinGapsBetweenBuildingChanges;
import org.confetti.xml.core.time.ConstraintActivitiesEndStudentsDay;
import org.confetti.xml.core.time.ConstraintActivitiesMaxSimultaneousInSelectedTimeSlots;
import org.confetti.xml.core.time.ConstraintActivitiesNotOverlapping;
import org.confetti.xml.core.time.ConstraintActivitiesOccupyMaxTimeSlotsFromSelection;
import org.confetti.xml.core.time.ConstraintActivitiesPreferredStartingTimes;
import org.confetti.xml.core.time.ConstraintActivitiesPreferredTimeSlots;
import org.confetti.xml.core.time.ConstraintActivitiesSameStartingDay;
import org.confetti.xml.core.time.ConstraintActivitiesSameStartingHour;
import org.confetti.xml.core.time.ConstraintActivitiesSameStartingTime;
import org.confetti.xml.core.time.ConstraintActivityEndsStudentsDay;
import org.confetti.xml.core.time.ConstraintActivityPreferredStartingTime;
import org.confetti.xml.core.time.ConstraintActivityPreferredStartingTimes;
import org.confetti.xml.core.time.ConstraintActivityPreferredTimeSlots;
import org.confetti.xml.core.time.ConstraintBasicCompulsoryTime;
import org.confetti.xml.core.time.ConstraintBreakTimes;
import org.confetti.xml.core.time.ConstraintMaxDaysBetweenActivities;
import org.confetti.xml.core.time.ConstraintMinDaysBetweenActivities;
import org.confetti.xml.core.time.ConstraintMinGapsBetweenActivities;
import org.confetti.xml.core.time.ConstraintStudentsActivityTagMaxHoursContinuously;
import org.confetti.xml.core.time.ConstraintStudentsActivityTagMaxHoursDaily;
import org.confetti.xml.core.time.ConstraintStudentsEarlyMaxBeginningsAtSecondHour;
import org.confetti.xml.core.time.ConstraintStudentsIntervalMaxDaysPerWeek;
import org.confetti.xml.core.time.ConstraintStudentsMaxGapsPerDay;
import org.confetti.xml.core.time.ConstraintStudentsMaxGapsPerWeek;
import org.confetti.xml.core.time.ConstraintStudentsMaxHoursContinuously;
import org.confetti.xml.core.time.ConstraintStudentsMaxHoursDaily;
import org.confetti.xml.core.time.ConstraintStudentsMinHoursDaily;
import org.confetti.xml.core.time.ConstraintStudentsSetActivityTagMaxHoursContinuously;
import org.confetti.xml.core.time.ConstraintStudentsSetActivityTagMaxHoursDaily;
import org.confetti.xml.core.time.ConstraintStudentsSetEarlyMaxBeginningsAtSecondHour;
import org.confetti.xml.core.time.ConstraintStudentsSetIntervalMaxDaysPerWeek;
import org.confetti.xml.core.time.ConstraintStudentsSetMaxGapsPerDay;
import org.confetti.xml.core.time.ConstraintStudentsSetMaxGapsPerWeek;
import org.confetti.xml.core.time.ConstraintStudentsSetMaxHoursContinuously;
import org.confetti.xml.core.time.ConstraintStudentsSetMaxHoursDaily;
import org.confetti.xml.core.time.ConstraintStudentsSetMinHoursDaily;
import org.confetti.xml.core.time.ConstraintStudentsSetNotAvailableTimes;
import org.confetti.xml.core.time.ConstraintSubactivitiesPreferredStartingTimes;
import org.confetti.xml.core.time.ConstraintSubactivitiesPreferredTimeSlots;
import org.confetti.xml.core.time.ConstraintTeacherActivityTagMaxHoursContinuously;
import org.confetti.xml.core.time.ConstraintTeacherActivityTagMaxHoursDaily;
import org.confetti.xml.core.time.ConstraintTeacherIntervalMaxDaysPerWeek;
import org.confetti.xml.core.time.ConstraintTeacherMaxDaysPerWeek;
import org.confetti.xml.core.time.ConstraintTeacherMaxGapsPerDay;
import org.confetti.xml.core.time.ConstraintTeacherMaxGapsPerWeek;
import org.confetti.xml.core.time.ConstraintTeacherMaxHoursContinuously;
import org.confetti.xml.core.time.ConstraintTeacherMaxHoursDaily;
import org.confetti.xml.core.time.ConstraintTeacherMinDaysPerWeek;
import org.confetti.xml.core.time.ConstraintTeacherMinHoursDaily;
import org.confetti.xml.core.time.ConstraintTeacherNotAvailableTimes;
import org.confetti.xml.core.time.ConstraintTeachersActivityTagMaxHoursContinuously;
import org.confetti.xml.core.time.ConstraintTeachersActivityTagMaxHoursDaily;
import org.confetti.xml.core.time.ConstraintTeachersIntervalMaxDaysPerWeek;
import org.confetti.xml.core.time.ConstraintTeachersMaxDaysPerWeek;
import org.confetti.xml.core.time.ConstraintTeachersMaxGapsPerDay;
import org.confetti.xml.core.time.ConstraintTeachersMaxGapsPerWeek;
import org.confetti.xml.core.time.ConstraintTeachersMaxHoursContinuously;
import org.confetti.xml.core.time.ConstraintTeachersMaxHoursDaily;
import org.confetti.xml.core.time.ConstraintTeachersMinDaysPerWeek;
import org.confetti.xml.core.time.ConstraintTeachersMinHoursDaily;
import org.confetti.xml.core.time.ConstraintThreeActivitiesGrouped;
import org.confetti.xml.core.time.ConstraintTwoActivitiesConsecutive;
import org.confetti.xml.core.time.ConstraintTwoActivitiesGrouped;
import org.confetti.xml.core.time.ConstraintTwoActivitiesOrdered;

public interface ConstraintXmlVisitor<R, P> {
	R visitSpace(ConstraintActivitiesOccupyMaxDifferentRooms c, P p);
	R visitSpace(ConstraintActivitiesSameRoomIfConsecutive c, P p);
	R visitSpace(ConstraintActivityPreferredRoom c, P p);
	R visitSpace(ConstraintActivityPreferredRooms c, P p);
	R visitSpace(ConstraintActivityTagPreferredRoom c, P p);
	R visitSpace(ConstraintActivityTagPreferredRooms c, P p);
	R visitSpace(ConstraintBasicCompulsorySpace c, P p);
	R visitSpace(ConstraintRoomNotAvailableTimes c, P p);
	R visitSpace(ConstraintStudentsMaxBuildingChangesPerDay c, P p);
	R visitSpace(ConstraintStudentsMaxBuildingChangesPerWeek c, P p);
	R visitSpace(ConstraintStudentsMinGapsBetweenBuildingChanges c, P p);
	R visitSpace(ConstraintStudentsSetHomeRoom c, P p);
	R visitSpace(ConstraintStudentsSetHomeRooms c, P p);
	R visitSpace(ConstraintStudentsSetMaxBuildingChangesPerDay c, P p);
	R visitSpace(ConstraintStudentsSetMaxBuildingChangesPerWeek c, P p);
	R visitSpace(ConstraintStudentsSetMinGapsBetweenBuildingChanges c, P p);
	R visitSpace(ConstraintSubjectActivityTagPreferredRoom c, P p);
	R visitSpace(ConstraintSubjectActivityTagPreferredRooms c, P p);
	R visitSpace(ConstraintSubjectPreferredRoom c, P p);
	R visitSpace(ConstraintSubjectPreferredRooms c, P p);
	R visitSpace(ConstraintTeacherHomeRoom c, P p);
	R visitSpace(ConstraintTeacherHomeRooms c, P p);
	R visitSpace(ConstraintTeacherMaxBuildingChangesPerDay c, P p);
	R visitSpace(ConstraintTeacherMaxBuildingChangesPerWeek c, P p);
	R visitSpace(ConstraintTeacherMinGapsBetweenBuildingChanges c, P p);
	R visitSpace(ConstraintTeachersMaxBuildingChangesPerDay c, P p);
	R visitSpace(ConstraintTeachersMaxBuildingChangesPerWeek c, P p);
	R visitSpace(ConstraintTeachersMinGapsBetweenBuildingChanges c, P p);
	R visitTime(ConstraintActivitiesEndStudentsDay c, P p);
	R visitTime(ConstraintActivitiesMaxSimultaneousInSelectedTimeSlots c, P p);
	R visitTime(ConstraintActivitiesNotOverlapping c, P p);
	R visitTime(ConstraintActivitiesOccupyMaxTimeSlotsFromSelection c, P p);
	R visitTime(ConstraintActivitiesPreferredStartingTimes c, P p);
	R visitTime(ConstraintActivitiesPreferredTimeSlots c, P p);
	R visitTime(ConstraintActivitiesSameStartingDay c, P p);
	R visitTime(ConstraintActivitiesSameStartingHour c, P p);
	R visitTime(ConstraintActivitiesSameStartingTime c, P p);
	R visitTime(ConstraintActivityEndsStudentsDay c, P p);
	R visitTime(ConstraintActivityPreferredStartingTime c, P p);
	R visitTime(ConstraintActivityPreferredStartingTimes c, P p);
	R visitTime(ConstraintActivityPreferredTimeSlots c, P p);
	R visitTime(ConstraintBasicCompulsoryTime c, P p);
	R visitTime(ConstraintBreakTimes c, P p);
	R visitTime(ConstraintMaxDaysBetweenActivities c, P p);
	R visitTime(ConstraintMinDaysBetweenActivities c, P p);
	R visitTime(ConstraintMinGapsBetweenActivities c, P p);
	R visitTime(ConstraintStudentsActivityTagMaxHoursContinuously c, P p);
	R visitTime(ConstraintStudentsActivityTagMaxHoursDaily c, P p);
	R visitTime(ConstraintStudentsEarlyMaxBeginningsAtSecondHour c, P p);
	R visitTime(ConstraintStudentsIntervalMaxDaysPerWeek c, P p);
	R visitTime(ConstraintStudentsMaxGapsPerDay c, P p);
	R visitTime(ConstraintStudentsMaxGapsPerWeek c, P p);
	R visitTime(ConstraintStudentsMaxHoursContinuously c, P p);
	R visitTime(ConstraintStudentsMaxHoursDaily c, P p);
	R visitTime(ConstraintStudentsMinHoursDaily c, P p);
	R visitTime(ConstraintStudentsSetActivityTagMaxHoursContinuously c, P p);
	R visitTime(ConstraintStudentsSetActivityTagMaxHoursDaily c, P p);
	R visitTime(ConstraintStudentsSetEarlyMaxBeginningsAtSecondHour c, P p);
	R visitTime(ConstraintStudentsSetIntervalMaxDaysPerWeek c, P p);
	R visitTime(ConstraintStudentsSetMaxGapsPerDay c, P p);
	R visitTime(ConstraintStudentsSetMaxGapsPerWeek c, P p);
	R visitTime(ConstraintStudentsSetMaxHoursContinuously c, P p);
	R visitTime(ConstraintStudentsSetMaxHoursDaily c, P p);
	R visitTime(ConstraintStudentsSetMinHoursDaily c, P p);
	R visitTime(ConstraintStudentsSetNotAvailableTimes c, P p);
	R visitTime(ConstraintSubactivitiesPreferredStartingTimes c, P p);
	R visitTime(ConstraintSubactivitiesPreferredTimeSlots c, P p);
	R visitTime(ConstraintTeacherActivityTagMaxHoursContinuously c, P p);
	R visitTime(ConstraintTeacherActivityTagMaxHoursDaily c, P p);
	R visitTime(ConstraintTeacherIntervalMaxDaysPerWeek c, P p);
	R visitTime(ConstraintTeacherMaxDaysPerWeek c, P p);
	R visitTime(ConstraintTeacherMaxGapsPerDay c, P p);
	R visitTime(ConstraintTeacherMaxGapsPerWeek c, P p);
	R visitTime(ConstraintTeacherMaxHoursContinuously c, P p);
	R visitTime(ConstraintTeacherMaxHoursDaily c, P p);
	R visitTime(ConstraintTeacherMinDaysPerWeek c, P p);
	R visitTime(ConstraintTeacherMinHoursDaily c, P p);
	R visitTime(ConstraintTeacherNotAvailableTimes c, P p);
	R visitTime(ConstraintTeachersActivityTagMaxHoursContinuously c, P p);
	R visitTime(ConstraintTeachersActivityTagMaxHoursDaily c, P p);
	R visitTime(ConstraintTeachersIntervalMaxDaysPerWeek c, P p);
	R visitTime(ConstraintTeachersMaxDaysPerWeek c, P p);
	R visitTime(ConstraintTeachersMaxGapsPerDay c, P p);
	R visitTime(ConstraintTeachersMaxGapsPerWeek c, P p);
	R visitTime(ConstraintTeachersMaxHoursContinuously c, P p);
	R visitTime(ConstraintTeachersMaxHoursDaily c, P p);
	R visitTime(ConstraintTeachersMinDaysPerWeek c, P p);
	R visitTime(ConstraintTeachersMinHoursDaily c, P p);
	R visitTime(ConstraintThreeActivitiesGrouped c, P p);
	R visitTime(ConstraintTwoActivitiesConsecutive c, P p);
	R visitTime(ConstraintTwoActivitiesGrouped c, P p);
	R visitTime(ConstraintTwoActivitiesOrdered c, P p);

}
