package org.confetti.xml.core;

import static java.util.Optional.of;
import static java.util.stream.Collectors.toList;
import static org.confetti.xml.core.BaseConstraintXml.newXmlConstraint;

import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

import org.confetti.core.Assignment;
import org.confetti.core.AssignmentGroup;
import org.confetti.core.DataProvider;
import org.confetti.core.NameableVisitee;
import org.confetti.dataprovider.xml.AssignmentGroupImpl;
import org.confetti.util.Tuple;

/**
 * @author Kárándi Tamás
 */
public class InstituteXmlBuilder {
	
	//--------------------------- Fields -------------------------------------------------------------------------------
	private final NameGetter nameGetter;
	private final Function<NameableVisitee, String> GET_NAME;

	//--------------------------- Constructors -------------------------------------------------------------------------
	public InstituteXmlBuilder() {
		this(new NameGetter());
	}
	
	public InstituteXmlBuilder(NameGetter nameGetter) {
		this.nameGetter = nameGetter;
		this.GET_NAME = nameable -> nameable.accept(nameGetter, null);
	}
	
	public Tuple<InstituteXml, List<Tuple<Long, Assignment>>> build(DataProvider dp) {
		InstituteXml inst = new InstituteXml(dp.getName().getValue(), "5.22.0", "generated by confetti");
		
		//Transforming Subjects, Teachers, StudentGroups, Buildings, Rooms, Days, Hours, Tags for FET
		inst.setSubjects(dp.getSubjects()			.toList(GET_NAME.andThen(SubjectXml::new)));
		inst.setTeachers(dp.getTeachers()			.toList(GET_NAME.andThen(TeacherXml::new)));
		inst.setYears(dp.getStudentGroups()			.toList(sg -> new YearXml(GET_NAME.apply(sg), sg)));
		inst.setBuildings(dp.getBuildings()			.toList(GET_NAME.andThen(BuildingXml::new)));
		inst.setRooms(dp.getRooms()					.toList(room -> new RoomXml(
																GET_NAME.apply(room),
																room.getBuilding().getValue().map(GET_NAME).orElse(""),
																room.getCapacity().getValue())));
		inst.setDays(new DaysXml(dp.getDays()		.toList(GET_NAME.andThen(DayXml::new))));
		inst.setHours(new HoursXml(dp.getHours()	.toList(GET_NAME.andThen(HourXml::new))));
		inst.setActivityTags(dp.getTags()			.toList(GET_NAME.andThen(ActivityTagXml::new)));
		
		//Transforming Assignments for FET and saving the newly assigned ids for further look up
		long counter = 1;
		Map<Assignment, Long> assgIds = new HashMap<>();
		List<Tuple<Long, Assignment>> tuples = new LinkedList<>();
		for (Assignment assignment : dp.getAssignments().getList()) {
			long newId = counter; //TODO: ((AssignmentImpl) assignment).getId();
			tuples.add(new Tuple<>(newId, assignment));
			assgIds.put(assignment, newId);
			counter++;
		}
		inst.setActivities(tuples.stream().map(this::createActivityXml).collect(toList()));

		//Transforming Constraints for FET
		ConstraintSetter setter = new ConstraintSetter(nameGetter, assg -> assgIds.get(assg));
		dp.getConstraints().getList().forEach(constr ->
			newXmlConstraint(inst, constr.getConstraintType(), constr.getAttributes().getValue(), setter));

		return new Tuple<>(inst, tuples);
	}
	
	//---------------------------- Helper methods ----------------------------------------------------------------------
	private ActivityXml createActivityXml(Tuple<Long, Assignment> tuple) {
		Long id = tuple.getFirst(); 
		Assignment assg = tuple.getSecond();
		int duration = assg.getDuration().getValue();
		long activityGroupId = assg.getGroup().getValue()
				.flatMap((AssignmentGroup x) -> of(((AssignmentGroupImpl) x).getId()))
				.orElse(0);
		int totalDuration = assg.getGroup().getValue()
				.flatMap(assGroup -> of(assGroup.getAssignments().stream()
					.map(ass -> ass.getDuration().getValue())
					.reduce(0, (a,b) -> a + b)))
				.orElse(duration); 
		
		return new ActivityXml(id, duration, activityGroupId, totalDuration,
			GET_NAME.apply(assg.getSubject()), 
      		assg.getTeachers().toList(GET_NAME),
      		assg.getStudentGroups().toList(GET_NAME),
      		assg.getTags().toList(GET_NAME));
	}
	
}
