package org.confetti.dataprovider.wizards;

import java.util.LinkedList;
import java.util.List;

import org.confetti.core.Day;
import org.confetti.core.Hour;
import org.confetti.fet.dataprovider.FETDataProvider;
import org.confetti.rcp.ConfettiPlugin;
import org.confetti.xml.core.Day_v5_24_0_Xml;
import org.confetti.xml.core.Days_v5_24_0_Xml;
import org.confetti.xml.core.Hour_v5_24_0_Xml;
import org.confetti.xml.core.Hours_v5_24_0_Xml;
import org.confetti.xml.core.InstituteXmlRelease;
import org.confetti.xml.core.Institute_v5_24_0_Xml;
import org.eclipse.jface.wizard.Wizard;

/**
 * @author Gabor Bubla
 */
public class NewFETWizard extends Wizard {

    private NewFETWizardModel model;

    public NewFETWizard(NewFETWizardModel model) {
        this.model = model;
    }
    
    @Override
    public void addPages() {
        setWindowTitle("New");
        addPage(new SaveFETFileWizardPage(model));
    }

    @Override
    public boolean performFinish() {
        try {
            Institute_v5_24_0_Xml xml = new Institute_v5_24_0_Xml(model.getDp().getName().getValue(), 
            		"5.3.23", "generated by confetti");

            List<Day_v5_24_0_Xml> days = new LinkedList<>();
            for (Day day : model.getDp().getDays().getList()) {
                days.add(new Day_v5_24_0_Xml(day.getName().getValue()));
            }
            xml.setDays(new Days_v5_24_0_Xml(days));

            List<Hour_v5_24_0_Xml> hours = new LinkedList<>();
            for (Hour hour : model.getDp().getHours().getList()) {
                hours.add(new Hour_v5_24_0_Xml(hour.getName().getValue()));
            }
            xml.setHours(new Hours_v5_24_0_Xml(hours));
            
            FETDataProvider dp = new FETDataProvider(xml, InstituteXmlRelease.v5_24_0, model.getFile());
            dp.save();
            
            ConfettiPlugin.getDefault().setDataProvider(dp, dp);
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
            return false;
        }
        return true;
    }

}
